const Database = require('better-sqlite3');
const path = require('path');
const fs = require('fs');

const dataDir = path.join(__dirname, '../../data');
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

const db = new Database(path.join(dataDir, 'zombies.sqlite'));

// WAL lets reads (leaderboards) and the occasional write (a /stats upsert)
// happen concurrently and speeds up writes. Safe for a single-process bot.
db.pragma('journal_mode = WAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS players (
    uuid                    TEXT    PRIMARY KEY,
    username                TEXT    NOT NULL,

    -- Overall
    wins_total              INTEGER DEFAULT 0,
    kills_total             INTEGER DEFAULT 0,
    deaths_total            INTEGER DEFAULT 0,
    rounds_total            INTEGER DEFAULT 0,
    doors_total             INTEGER DEFAULT 0,
    windows_total           INTEGER DEFAULT 0,
    knocks_total            INTEGER DEFAULT 0,
    revives_total           INTEGER DEFAULT 0,
    headshots_total         INTEGER DEFAULT 0,
    bullets_hit_total       INTEGER DEFAULT 0,
    bullets_shot_total      INTEGER DEFAULT 0,

    -- Per-map total wins
    wins_deadend            INTEGER DEFAULT 0,
    wins_badblood           INTEGER DEFAULT 0,
    wins_alienarcadium      INTEGER DEFAULT 0,
    wins_prison             INTEGER DEFAULT 0,

    -- Dead End per difficulty + fastest win (r30) + milestones
    wins_deadend_normal     INTEGER DEFAULT 0,
    wins_deadend_hard       INTEGER DEFAULT 0,
    wins_deadend_rip        INTEGER DEFAULT 0,
    fastest_deadend_normal  INTEGER,
    fastest_deadend_hard    INTEGER,
    fastest_deadend_rip     INTEGER,
    r10_deadend_normal      INTEGER,
    r20_deadend_normal      INTEGER,
    r10_deadend_hard        INTEGER,
    r20_deadend_hard        INTEGER,
    r10_deadend_rip         INTEGER,
    r20_deadend_rip         INTEGER,

    -- Dead End extended stats (totals + per difficulty)
    kills_deadend_total     INTEGER DEFAULT 0,
    kills_deadend_normal    INTEGER DEFAULT 0,
    kills_deadend_hard      INTEGER DEFAULT 0,
    kills_deadend_rip       INTEGER DEFAULT 0,
    deaths_deadend_total    INTEGER DEFAULT 0,
    deaths_deadend_normal   INTEGER DEFAULT 0,
    deaths_deadend_hard     INTEGER DEFAULT 0,
    deaths_deadend_rip      INTEGER DEFAULT 0,
    rounds_deadend_total    INTEGER DEFAULT 0,
    rounds_deadend_normal   INTEGER DEFAULT 0,
    rounds_deadend_hard     INTEGER DEFAULT 0,
    rounds_deadend_rip      INTEGER DEFAULT 0,
    doors_deadend_total     INTEGER DEFAULT 0,
    doors_deadend_normal    INTEGER DEFAULT 0,
    doors_deadend_hard      INTEGER DEFAULT 0,
    doors_deadend_rip       INTEGER DEFAULT 0,
    windows_deadend_total   INTEGER DEFAULT 0,
    windows_deadend_normal  INTEGER DEFAULT 0,
    windows_deadend_hard    INTEGER DEFAULT 0,
    windows_deadend_rip     INTEGER DEFAULT 0,
    knocks_deadend_total    INTEGER DEFAULT 0,
    knocks_deadend_normal   INTEGER DEFAULT 0,
    knocks_deadend_hard     INTEGER DEFAULT 0,
    knocks_deadend_rip      INTEGER DEFAULT 0,
    revives_deadend_total   INTEGER DEFAULT 0,
    revives_deadend_normal  INTEGER DEFAULT 0,
    revives_deadend_hard    INTEGER DEFAULT 0,
    revives_deadend_rip     INTEGER DEFAULT 0,

    -- Bad Blood per difficulty + fastest win (r30) + milestones
    wins_badblood_normal    INTEGER DEFAULT 0,
    wins_badblood_hard      INTEGER DEFAULT 0,
    wins_badblood_rip       INTEGER DEFAULT 0,
    fastest_badblood_normal INTEGER,
    fastest_badblood_hard   INTEGER,
    fastest_badblood_rip    INTEGER,
    r10_badblood_normal     INTEGER,
    r20_badblood_normal     INTEGER,
    r10_badblood_hard       INTEGER,
    r20_badblood_hard       INTEGER,
    r10_badblood_rip        INTEGER,
    r20_badblood_rip        INTEGER,

    -- Bad Blood extended stats
    kills_badblood_total    INTEGER DEFAULT 0,
    kills_badblood_normal   INTEGER DEFAULT 0,
    kills_badblood_hard     INTEGER DEFAULT 0,
    kills_badblood_rip      INTEGER DEFAULT 0,
    deaths_badblood_total   INTEGER DEFAULT 0,
    deaths_badblood_normal  INTEGER DEFAULT 0,
    deaths_badblood_hard    INTEGER DEFAULT 0,
    deaths_badblood_rip     INTEGER DEFAULT 0,
    rounds_badblood_total   INTEGER DEFAULT 0,
    rounds_badblood_normal  INTEGER DEFAULT 0,
    rounds_badblood_hard    INTEGER DEFAULT 0,
    rounds_badblood_rip     INTEGER DEFAULT 0,
    doors_badblood_total    INTEGER DEFAULT 0,
    doors_badblood_normal   INTEGER DEFAULT 0,
    doors_badblood_hard     INTEGER DEFAULT 0,
    doors_badblood_rip      INTEGER DEFAULT 0,
    windows_badblood_total  INTEGER DEFAULT 0,
    windows_badblood_normal INTEGER DEFAULT 0,
    windows_badblood_hard   INTEGER DEFAULT 0,
    windows_badblood_rip    INTEGER DEFAULT 0,
    knocks_badblood_total   INTEGER DEFAULT 0,
    knocks_badblood_normal  INTEGER DEFAULT 0,
    knocks_badblood_hard    INTEGER DEFAULT 0,
    knocks_badblood_rip     INTEGER DEFAULT 0,
    revives_badblood_total  INTEGER DEFAULT 0,
    revives_badblood_normal INTEGER DEFAULT 0,
    revives_badblood_hard   INTEGER DEFAULT 0,
    revives_badblood_rip    INTEGER DEFAULT 0,

    -- Alien Arcadium (no difficulties)
    fastest_alienarcadium      INTEGER,
    r10_alienarcadium          INTEGER,
    r20_alienarcadium          INTEGER,
    total_rounds_alienarcadium INTEGER DEFAULT 0,
    kills_alienarcadium        INTEGER DEFAULT 0,
    deaths_alienarcadium       INTEGER DEFAULT 0,
    doors_alienarcadium        INTEGER DEFAULT 0,
    windows_alienarcadium      INTEGER DEFAULT 0,
    knocks_alienarcadium       INTEGER DEFAULT 0,
    revives_alienarcadium      INTEGER DEFAULT 0,

    -- Prison per difficulty + fastest win (r30) + milestones
    wins_prison_normal      INTEGER DEFAULT 0,
    wins_prison_hard        INTEGER DEFAULT 0,
    wins_prison_rip         INTEGER DEFAULT 0,
    fastest_prison_normal   INTEGER,
    fastest_prison_hard     INTEGER,
    fastest_prison_rip      INTEGER,
    r10_prison_normal       INTEGER,
    r20_prison_normal       INTEGER,
    r10_prison_hard         INTEGER,
    r20_prison_hard         INTEGER,
    r10_prison_rip          INTEGER,
    r20_prison_rip          INTEGER,

    -- Best round reached (per map + difficulty)
    best_round_total            INTEGER DEFAULT 0,
    best_round_deadend          INTEGER DEFAULT 0,
    best_round_deadend_normal   INTEGER DEFAULT 0,
    best_round_deadend_hard     INTEGER DEFAULT 0,
    best_round_deadend_rip      INTEGER DEFAULT 0,
    best_round_badblood         INTEGER DEFAULT 0,
    best_round_badblood_normal  INTEGER DEFAULT 0,
    best_round_badblood_hard    INTEGER DEFAULT 0,
    best_round_badblood_rip     INTEGER DEFAULT 0,
    best_round_alienarcadium    INTEGER DEFAULT 0,
    best_round_prison           INTEGER DEFAULT 0,
    best_round_prison_normal    INTEGER DEFAULT 0,
    best_round_prison_hard      INTEGER DEFAULT 0,
    best_round_prison_rip       INTEGER DEFAULT 0,

    -- Prison extended stats
    kills_prison_total      INTEGER DEFAULT 0,
    kills_prison_normal     INTEGER DEFAULT 0,
    kills_prison_hard       INTEGER DEFAULT 0,
    kills_prison_rip        INTEGER DEFAULT 0,
    deaths_prison_total     INTEGER DEFAULT 0,
    deaths_prison_normal    INTEGER DEFAULT 0,
    deaths_prison_hard      INTEGER DEFAULT 0,
    deaths_prison_rip       INTEGER DEFAULT 0,
    rounds_prison_total     INTEGER DEFAULT 0,
    rounds_prison_normal    INTEGER DEFAULT 0,
    rounds_prison_hard      INTEGER DEFAULT 0,
    rounds_prison_rip       INTEGER DEFAULT 0,
    doors_prison_total      INTEGER DEFAULT 0,
    doors_prison_normal     INTEGER DEFAULT 0,
    doors_prison_hard       INTEGER DEFAULT 0,
    doors_prison_rip        INTEGER DEFAULT 0,
    windows_prison_total    INTEGER DEFAULT 0,
    windows_prison_normal   INTEGER DEFAULT 0,
    windows_prison_hard     INTEGER DEFAULT 0,
    windows_prison_rip      INTEGER DEFAULT 0,
    knocks_prison_total     INTEGER DEFAULT 0,
    knocks_prison_normal    INTEGER DEFAULT 0,
    knocks_prison_hard      INTEGER DEFAULT 0,
    knocks_prison_rip       INTEGER DEFAULT 0,
    revives_prison_total    INTEGER DEFAULT 0,
    revives_prison_normal   INTEGER DEFAULT 0,
    revives_prison_hard     INTEGER DEFAULT 0,
    revives_prison_rip      INTEGER DEFAULT 0,

    raw_json                TEXT    NOT NULL,
    last_updated            INTEGER NOT NULL
  )
`);

const migrations = [
  // Original migrations
  'ALTER TABLE players ADD COLUMN kills_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN wins_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN wins_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN wins_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN fastest_deadend_normal INTEGER',
  'ALTER TABLE players ADD COLUMN fastest_deadend_hard INTEGER',
  'ALTER TABLE players ADD COLUMN fastest_deadend_rip INTEGER',
  'ALTER TABLE players ADD COLUMN wins_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN wins_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN wins_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN fastest_badblood_normal INTEGER',
  'ALTER TABLE players ADD COLUMN fastest_badblood_hard INTEGER',
  'ALTER TABLE players ADD COLUMN fastest_badblood_rip INTEGER',
  'ALTER TABLE players ADD COLUMN fastest_alienarcadium INTEGER',
  'ALTER TABLE players ADD COLUMN wins_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN wins_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN wins_prison_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN fastest_prison_normal INTEGER',
  'ALTER TABLE players ADD COLUMN fastest_prison_hard INTEGER',
  'ALTER TABLE players ADD COLUMN fastest_prison_rip INTEGER',
  'ALTER TABLE players ADD COLUMN r10_deadend_normal INTEGER',
  'ALTER TABLE players ADD COLUMN r20_deadend_normal INTEGER',
  'ALTER TABLE players ADD COLUMN r10_deadend_hard INTEGER',
  'ALTER TABLE players ADD COLUMN r20_deadend_hard INTEGER',
  'ALTER TABLE players ADD COLUMN r10_deadend_rip INTEGER',
  'ALTER TABLE players ADD COLUMN r20_deadend_rip INTEGER',
  'ALTER TABLE players ADD COLUMN r10_badblood_normal INTEGER',
  'ALTER TABLE players ADD COLUMN r20_badblood_normal INTEGER',
  'ALTER TABLE players ADD COLUMN r10_badblood_hard INTEGER',
  'ALTER TABLE players ADD COLUMN r20_badblood_hard INTEGER',
  'ALTER TABLE players ADD COLUMN r10_badblood_rip INTEGER',
  'ALTER TABLE players ADD COLUMN r20_badblood_rip INTEGER',
  'ALTER TABLE players ADD COLUMN r10_alienarcadium INTEGER',
  'ALTER TABLE players ADD COLUMN r20_alienarcadium INTEGER',
  'ALTER TABLE players ADD COLUMN r10_prison_normal INTEGER',
  'ALTER TABLE players ADD COLUMN r20_prison_normal INTEGER',
  'ALTER TABLE players ADD COLUMN r10_prison_hard INTEGER',
  'ALTER TABLE players ADD COLUMN r20_prison_hard INTEGER',
  'ALTER TABLE players ADD COLUMN r10_prison_rip INTEGER',
  'ALTER TABLE players ADD COLUMN r20_prison_rip INTEGER',
  'ALTER TABLE players ADD COLUMN total_rounds_alienarcadium INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_alienarcadium INTEGER DEFAULT 0',
  // Global extended stats
  'ALTER TABLE players ADD COLUMN rounds_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN headshots_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN bullets_hit_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN bullets_shot_total INTEGER DEFAULT 0',
  // Dead End extended
  'ALTER TABLE players ADD COLUMN kills_deadend_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_deadend_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_deadend_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_deadend_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_deadend_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_deadend_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_deadend_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_deadend_rip INTEGER DEFAULT 0',
  // Bad Blood extended
  'ALTER TABLE players ADD COLUMN kills_badblood_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_badblood_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_badblood_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_badblood_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_badblood_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_badblood_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_badblood_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_badblood_rip INTEGER DEFAULT 0',
  // AA extended
  'ALTER TABLE players ADD COLUMN deaths_alienarcadium INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_alienarcadium INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_alienarcadium INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_alienarcadium INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_alienarcadium INTEGER DEFAULT 0',
  // Prison extended
  'ALTER TABLE players ADD COLUMN kills_prison_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN kills_prison_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_prison_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN deaths_prison_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_prison_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN rounds_prison_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_prison_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN doors_prison_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_prison_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN windows_prison_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_prison_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN knocks_prison_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_prison_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN revives_prison_rip INTEGER DEFAULT 0',
  // Best round columns
  'ALTER TABLE players ADD COLUMN best_round_total INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_deadend INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_deadend_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_deadend_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_deadend_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_badblood INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_badblood_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_badblood_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_badblood_rip INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_alienarcadium INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_prison INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_prison_normal INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_prison_hard INTEGER DEFAULT 0',
  'ALTER TABLE players ADD COLUMN best_round_prison_rip INTEGER DEFAULT 0',
];

for (const sql of migrations) {
  try { db.exec(sql); } catch (_) {}
}

// Index every column a leaderboard sorts by, so ORDER BY / rank lookups walk a
// pre-sorted structure instead of scanning the whole table. Derived from the
// leaderboard config so it always matches the queryable columns. (Mob-kill
// leaderboards use json_extract and aren't covered by these.)
const { LEADERBOARDS } = require('../leaderboards/config');
const indexCols = [...new Set(LEADERBOARDS.filter(lb => lb.col).map(lb => lb.col))];
for (const col of indexCols) {
  // col comes from trusted config (never user input), so interpolation is safe.
  try { db.exec(`CREATE INDEX IF NOT EXISTS idx_${col} ON players(${col})`); } catch (_) {}
}

module.exports = db;
